Not(
    Or(
        Or(
            Or(
                Or(
                    Or(
                        Or(
                            Or(
                                Or(
                                    Or(
                                        Or(
                                            Or(
                                                Or(
                                                    Or(
                                                        Or(
                                                            InformationPanelBar.IsPanelOpen('politics'), InformationPanelBar.IsPanelOpen('politics_panel_change_law')
                                                        ), 
                                                        InformationPanelBar.IsPanelOpen('tech_tree')
                                                    ),
                                                    InformationPanelBar.IsPanelOpen('market')
                                                ),
                                                InformationPanelBar.IsPanelOpen('production_methods')
                                            ),
                                            InformationPanelBar.IsPanelOpen('military')
                                        ),
                                        InformationPanelBar.IsPanelOpen('diplomatic_overview')
                                    ),
                                    InformationPanelBar.IsPanelOpen('budget')
                                ),
                                InformationPanelBar.IsPanelOpen('companies')
                            ),
                            InformationPanelBar.IsPanelOpen('culture')
                        ),
                        InformationPanelBar.IsPanelOpen('pops_overview')
                    ),
                    InformationPanelBar.IsPanelOpen('journal')
                ),
                InformationPanelBar.IsPanelOpen('outliner')
            ),
             MapListPanelManager.IsVisible
        ),
        GetVariableSystem.Exists('ve_tab_var')
    )
)



Not(
    Or(
        Or(
            Or(
                Or(
                    Or(
                        Or(
                            Or(
                                Or(
                                    Or(
                                        Or(
                                            Or(
                                                Or(
                                                    Or(
                                                        Or(
                                                            InformationPanelBar.IsPanelOpen('politics'), InformationPanelBar.IsPanelOpen('politics_panel_change_law')
                                                        ), 
                                                        InformationPanelBar.IsPanelOpen('tech_tree')
                                                    ),
                                                    InformationPanelBar.IsPanelOpen('market')
                                                ),
                                                InformationPanelBar.IsPanelOpen('production_methods')
                                            ),
                                            InformationPanelBar.IsPanelOpen('military')
                                        ),
                                        InformationPanelBar.IsPanelOpen('diplomatic_overview')
                                    ),
                                    InformationPanelBar.IsPanelOpen('budget')
                                ),
                                InformationPanelBar.IsPanelOpen('companies')
                            ),
                            InformationPanelBar.IsPanelOpen('culture')
                        ),
                        InformationPanelBar.IsPanelOpen('pops_overview')
                    ),
                    InformationPanelBar.IsPanelOpen('journal')
                ),
                InformationPanelBar.IsPanelOpen('outliner')
            ),
             MapListPanelManager.IsVisible
        ),
        GetVariableSystem.Exists('ve_tab_var')
    )
)
